### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Faris90** [m-byte/Cigar#617]
I am using an old version of cigar:
  ____ _                  ____            _           _   
 / ___(_) __ _  __ _ _ __|  _ \ _ __ ___ (_) ___  ___| |_ 
| |   | |/ _` |/ _` | '__| |_) | '__/ _ \| |/ _ \/ __| __|
| |___| | (_| | (_| | |  |  __/| | | (_) | |  __/ (__| |_ 
 \____|_|\__, |\__,_|_|  |_|   |_|  \___// |\___|\___|\__|
         |___/ - Better than Ogar!     |__/               
-------------------------------------------------------
[Master] Master Server started at port port 1111
[Game:1] Game Server started at port 8080
[Game:1] Stats Server started at port 5555
[Game:1] Current game mode is Free For All
timers.js:348
    throw new TypeError('"callback" argument must be a function');
    ^

TypeError: "callback" argument must be a function
    at exports.setTimeout (timers.js:348:11)
    at GameServer.mainLoop (/home/ubuntu/workspace/server/GameServer.js:440:13)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

How could I fix it, I dont want to use something else

**Comment by TopoR1** [comment]
Download 5 version of NodeJS and everything will work.

**Comment by Faris90** [comment]
I use cloud9

**Comment by SuperOP535** [comment]
then do nvm install yourversion
and nvm alias default yourversion
@Faris90
